### ISSUE TITLE
Test failure bij stap "update een gebruiker"

### ISSUE THREAD

**Issue by Hion-V** [feddevanderlist/workshop#1]
De tests zouden volgens de screenshoot allemaal succesvol uit moeten voeren maar dit is niet het geval.
![Screenshot_2023-01-16_12-45-34](https://user-images.githubusercontent.com/6537945/212671169-653f4c07-7d50-49ed-b36e-618c2b449290.png)

**Comment by fietser97** [comment]
opgelost in de laatste push
